apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: consume-configmap
  namespace: {{ .Release.Namespace }}
data:  
  TZ: America/Tijuana 
  SERVICE_TEST: http://{{ .Values.cimapass.deployment.helloApi.service.name }}:{{ .Values.cimapass.deployment.helloApi.service.port }}