apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cimapass.deployment.helloApi.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hello-api
  type: {{ .Values.cimapass.deployment.helloApi.service.type }}    
  ports:
    - protocol: TCP
      port: {{ .Values.cimapass.deployment.helloApi.service.port }}
      {{- if or (eq "NodePort" .Values.cimapass.deployment.helloApi.service.type) (eq "ClusterIP" .Values.cimapass.deployment.helloApi.service.type) }}      
      targetPort: 3000
      {{- else }}
        {{- fail "Invalid service type. Service type must be NodePort or ClusterIP" }}
      {{- end }}